### ISSUE TITLE
Stremio server not working if reversed proxy used

### ISSUE THREAD

**Issue by alanmilinovic** [n0bodysec/docker-images#10]
Hi, I am trying to make stremio work with reversed proxy, but stremio server just don't work, it seams that url is not correct.

```
<VirtualHost *:20530>
	<Location "/stremio/">
		ProxyPass http://localhost:7080/
		ProxyPassReverse http://localhost:7080/
	</Location>
	<Location "/stremioserver">
		ProxyPass http://localhost:11470
		ProxyPassReverse http://localhost:11470
	</Location>
</VirtualHost>
```

URL specified in stremio web:
with proxy: http://192.168.188.203:11470/
no proxy: http://192.168.188.203:20530/stremioserver/

This is the link for example that I am getting once the video starts when using directly (no proxy):
http://192.168.188.203:11470/571726bee423983ff34431f319209e48be784667/0/stats.json

and this is the link that I get if I use stremio server as proxy (404 error):
http://192.168.188.203:20530/571726bee423983ff34431f319209e48be784667/0/stats.json

This is how it should be correctly:
http://192.168.188.203:20530/stremioserver/571726bee423983ff34431f319209e48be784667/0/stats.json

If I test server by executing below line it is working fine:
http://192.168.188.203:20530/stremioserver/settings

Is it possible to configure base url for the server or something? Any idea, please.

**Comment by alanmilinovic** [comment]
I tried with exposing direct port not via location and now I am getting error 500. Strange is that when I click "Download this video" or "Copy stream link" it is downloading video normally and url is pointing to correct https address.

**Comment by n0bodysec** [comment]
Hello. If I remember correctly, that's a known issue of Stremio.
Please try to use another subdomain for the stremio server!

Regards.

**Comment by alanmilinovic** [comment]
Yes, correct, I used directly without location and it works.

Now I tried to use https and am getting error 500.
`{"error":{"code":10,"message":"Failed to read hls playlist: Probe process exited with code: 1"}}`

When I click on Download this video or Copy video link it is working fine.

Same video is playing fine with http protocol.

Any idea?

**Comment by n0bodysec** [comment]
It works on my end!

**Comment by alanmilinovic** [comment]
> It works on my end!

Hm, I am using a subdomain. Could be a reason maybe?

**Comment by n0bodysec** [comment]
> Hm, I am using a subdomain. Could be a reason maybe?

I tested it with two subdomains:
- stremio.domain.tld
- stremio-server.domain.tld

It should work. I remember that Stremio had issues with some videos in the past.

Also you are using apache as a reverse proxy, I recommend you to try nginx.

**Comment by alanmilinovic** [comment]
> > Hm, I am using a subdomain. Could be a reason maybe?
> 
> I tested it with two subdomains:
> 
> * stremio.domain.tld
> * stremio-server.domain.tld
> 
> It should work. I remember that Stremio had issues with some videos in the past.
> 
> Also you are using apache as a reverse proxy, I recommend you to try nginx.

Thank you very much for putting the effort.

Can you also test it with port, like this:
- stremio.domain.ltd:20537

My machine is under VPN and I am port forwarding on the VPN backend, therefore I cannot use port 443 as it is already taken by some other VPN subscriber.

**Comment by n0bodysec** [comment]
It works as expected.

**Comment by alanmilinovic** [comment]
Yes, I can see it is working for me as well now, but not for all videos. I guess it is Chrome that is blocking for some video streams.
