### ISSUE TITLE
[Stremio] Any way to set the default IP?

### ISSUE THREAD

**Issue by danperks** [n0bodysec/docker-images#4]
Hey, I'm running this locally and both ends individually work fine.

The WebUI has a default IP of 127.0.0.1 but that doesn't work out the box. Only when I set the IP to that of the machine running this image (192.168.0.XX) does it then seem to work. I would assume 127.0.0.1 only works when the machine you are accessing the WebUI from is also the machine running the container.

Is there a way to set the default server IP, so that my friends on the same network do not have to each set the IP of the server the first time they connect? 

Thanks :)

**Comment by n0bodysec** [comment]
Hey!

Unfortunately, I don't think so :(

I think the default server url is defined in `stremio-core` package.
https://github1s.com/Stremio/stremio-core/blob/HEAD/src/constants.rs#L47-L48

You can rebuild stremio-web with a custom version of stremio-core, but it's not easily portable.

Another way is to hot patch the WebAssembly binary (`web/binaries/stremio_core_web_bg.wasm`). I can check this.

**Comment by n0bodysec** [comment]
Hey @danperks!

After some research, I found that the `streamingServer` query component isn't implemented on `stremio-web` ([reference](https://github.com/Stremio/stremio-web/issues/295#issuecomment-1199020346)).  
So I added a local copy of the staging stremio-shell Web UI (https://staging.strem.io/) accessible on port `8081` (see https://github.com/n0bodysec/docker-images/commit/777414624c9dbb31f7c9c440f258fdd085dcc0dc).

So now, you can reach the old webui (the one that supports the `streaminServer` query component) at: http://stremio:8081

Example usage: http://stremio:8081/?streamingServer=http://stremio:11470

I hope this solves your problem!

**Comment by danperks** [comment]
I'll give it a try later on, thanks for the help.

**Comment by n0bodysec** [comment]
You are welcome!

**Comment by Pfuenzle** [comment]
Is there a way to do this for the new Web-UI, for example by patching the web assembly? Or is this only supported by the old UI? The query parameter does not seem to work on the new one

**Comment by n0bodysec** [comment]
> Is there a way to do this for the new Web-UI, for example by patching the web assembly? Or is this only supported by the old UI? The query parameter does not seem to work on the new one

The query component is not implemented on the new UI. I tried to patch the WebAssembly binary (see https://github.com/n0bodysec/docker-images/issues/4#issuecomment-1266086307), but the binary gets corrupted.

Btw I like the idea you mention in https://github.com/n0bodysec/docker-images/issues/5#issuecomment-1299983762.
