### ISSUE TITLE
Stremio Change ports

### ISSUE THREAD

**Issue by alanmilinovic** [n0bodysec/docker-images#8]
How to change default ports? I tried to modify `run.sh` and `docker-compose.yml`

```
http-server web/ -p 7080 -d false &
http-server shell/ -p 7081 -d false &
```

```
    ports:
      - '11470:11470'
      - '12470:12470'
      - '7080:7080'
      - '7081:7081'
```

But when I check container log it shows default ports used:

```
Applying patches...
Executing patch patches/FIX_UNSUPPORTED_MEDIA.sh
Applying patch for HTTP 415 Unsupported Media Type...
Starting up http-server, serving shell/
http-server version: 14.1.1
http-server settings: 
CORS: disabled
Cache: 3600 seconds
Connection Timeout: 120 seconds
Directory Listings: not visible
AutoIndex: visible
Serve GZIP Files: false
Serve Brotli Files: false
Default File Extension: none
Available on:
  http://127.0.0.1:8081
  http://172.31.0.2:8081
Hit CTRL-C to stop the server
Starting up http-server, serving web/
http-server version: 14.1.1
http-server settings: 
CORS: disabled
Cache: 3600 seconds
Connection Timeout: 120 seconds
Directory Listings: not visible
AutoIndex: visible
Serve GZIP Files: false
Serve Brotli Files: false
Default File Extension: none
Available on:
  http://127.0.0.1:8080
  http://172.31.0.2:8080
```

**Comment by n0bodysec** [comment]
Hello. Which port are you trying to change? Usually you don't need to change the internal port. You can just map it to another port on the host.

For example, if you want the port `8080` to be available under the port `7080` on the host, you only need to change the port before `:`. Example: `7080:8080`.

You can always check the Docker docs.

https://docs.docker.com/compose/compose-file/compose-file-v3/#ports
https://docs.docker.com/compose/networking/
https://docs.docker.com/network/#published-ports

Regards.

**Comment by alanmilinovic** [comment]
Yes, you are right, thanks. I just uncommented "build: ." part in compose yaml file to rebuild the image and get the latest web interface.

**Comment by n0bodysec** [comment]
You are welcome. I'm glad it worked for you!

Regards.
