### ISSUE TITLE
Stremio stremio-web update to the latest version

### ISSUE THREAD

**Issue by alanmilinovic** [n0bodysec/docker-images#9]
Just a simple question, how often do you update stremio-web in your image? I can see you are two releases behind, latest version is 5.0.0-beta.2 and in your image it is 5.0.0-beta.0.

**Comment by n0bodysec** [comment]
Hello! I usually do not update the image published to the docker hub. I'll setup a GH Action to update it automatically!

**Comment by alanmilinovic** [comment]
> Hello! I usually do not update the image published to the docker hub. I'll setup a GH Action to update it automatically!

Can you give me instructions please how to do it?

**Comment by n0bodysec** [comment]
The GH action will automatically update the docker hub image. In the meantime, if you want an updated version, you can build the image locally yourself.

You can comment the `image` key on the `docker-compose.yml` and the simply uncomment the `build` key. Next time you start the container using docker compose, it will build a local copy of the image.

**Comment by alanmilinovic** [comment]
Just uncommented build and after rebuild was done. Streamio server stopped working. 

`Cannot GET /stremio_server/`

Any idea?

**Comment by n0bodysec** [comment]
I've pushed a fix. I haven't tested it because I can't do it now, but it should work!

**Comment by alanmilinovic** [comment]
> I've pushed a fix. I haven't tested it because I can't do it now, but it should work!

Still it doesn't work.

**Comment by alanmilinovic** [comment]
Sorry, it is working now. I forgot to comment image in compose file. Thank you!

**Comment by n0bodysec** [comment]
You are welcome!
